"""empty message

Revision ID: 593798ad38fd
Revises: 5637acbd2713
Create Date: 2024-01-11 11:45:01.403488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593798ad38fd'
down_revision = '5637acbd2713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
