"""empty message

Revision ID: 63fa3ea68783
Revises: 7c2460f62e5e
Create Date: 2024-01-11 12:41:50.973025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fa3ea68783'
down_revision = '7c2460f62e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
