"""empty message

Revision ID: 718319b3a377
Revises: a9f2621bbb4d
Create Date: 2024-02-13 14:28:51.315935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718319b3a377'
down_revision = 'a9f2621bbb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
