"""empty message

Revision ID: 7dee15605594
Revises: ada083c14dc4
Create Date: 2023-12-29 00:52:59.582864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dee15605594'
down_revision = 'ada083c14dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('month')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
