"""empty message

Revision ID: a9f2621bbb4d
Revises: 8c683c3829dc
Create Date: 2024-02-12 14:53:05.036363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f2621bbb4d'
down_revision = '8c683c3829dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.drop_column('mobile_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
